feat(host): create a header component
dreyliky/angular-community-ua-frontend pull request #29
Opened 2023-02-09 14:20 UTC by br1ttan

2023-02-09 14:20 UTC, br1ttan commented
минулий пулл реквест я видалив бо знов натикав щось не так

2023-02-09 15:01 UTC, br1ttan commented
якщо можеш і будеш мержити то краще перейменувати як: chore(host): moved height properties

2023-02-10 10:27 UTC, dreyliky requested changes

2023-02-10 10:27 UTC, dreyliky commented on apps/host/src/app/pages/home/components/header/header-user/header-user.component.html
> +    <svg
Треба винести цю іконку в локальні assets як `svg` файл

2023-02-10 10:27 UTC, dreyliky commented on apps/host/src/app/pages/home/components/header/header-user/header-user.component.scss
> +        img {
Краще використовувати класи в якості селекторів, замість тегів

2023-02-10 10:27 UTC, dreyliky commented on apps/code-review/src/styles.scss
> +    color: hsla(0, 0%, 80%, 0.587);
Давай винесемо все ж таки опис кольорів в `libs/assets`.

І в `host` + `code-review` підключимо цей файл ось так в `project.json` в `styles`:
```
"libs/assets/src/lib/styles/variables.scss"
```

**variables.scss**
```
:root {
    --text-color: 204,204,204;
    --background-color: 32,35,39;
}
```

Usage:
`color: rgb(var(--text-color))`;
`background-color: rgb(var(--background-color))`;

2023-02-10 10:27 UTC, dreyliky commented on apps/host/src/app/pages/home/components/header/header-user/header-user.component.ts
> +    public readonly codeReviewLink = '/code-review';
Цей `path` має бути взятий з enum. Нажаль я не додивився на код-ревью і цей path прописаний в неправильному enum, то ж прошу тебе виправити це.

Зараз цей path в `AppRouteEnum`. А має бути в `HomeRouteEnum`.

Так само, там немає `index.ts` файлів. Виправ це для тих єнамів пліз. Дякую!

2023-02-10 10:27 UTC, dreyliky commented on apps/host/src/app/pages/home/components/header/header.component.html
> +        Спільнота
Давай зробимо цей текст на рівні цього компоненту таким кольором: `#f1f1f1`.

2023-02-10 10:27 UTC, dreyliky commented on apps/host/src/app/pages/home/components/header/header.component.scss
> +    header {
Селектор має бути класом, а не тегом

2023-02-10 10:27 UTC, dreyliky commented on apps/host/src/styles.scss
> +    color: hsla(0, 0%, 80%, 0.587);
Також, замінити це на глобальні змінні

2023-02-10 10:27 UTC, dreyliky commented on apps/host/src/app/pages/home/components/header/header-user/header-user.component.html
> +<button class="user-button" [matMenuTriggerFor]="menu">
Давай перейменуємо цей компонент на `user-menu.component`

2023-02-10 10:27 UTC, dreyliky commented on apps/host/src/app/pages/home/components/header/header.module.ts
> +import { HeaderUserComponent } from './header-user/header-user.component';
Відсутній index.ts

2023-02-10 17:00 UTC, dreyliky approved these changes

2023-02-10 17:02 UTC, merged