feat(code-review): made request table with user project information
dreyliky/angular-community-ua-frontend pull request #37
Opened 2023-02-13 07:51 UTC by yatsivroge

2023-02-13 12:45 UTC, dreyliky requested changes

2023-02-13 12:45 UTC, dreyliky commented on apps/code-review/src/app/core/enums/code-review-status-enum.ts
> +export enum CodeReviewStatusEnum {
Давай перемістимо цей єнам в `app/enums`. Також назвемо його `CodeReviewRequestStatusEnum`.

Також в назві файлу `enum` з обох сторін має бути розділений крапкою.

2023-02-13 12:45 UTC, dreyliky commented on apps/code-review/src/app/core/interfaces/code-review-request.interface.ts
> +import { CodeReviewStatusEnum } from '@code-review/core';
Давай перемістимо це в `app/interfaces`

2023-02-13 12:45 UTC, dreyliky commented on apps/code-review/src/app/core/interfaces/code-review-request.interface.ts
> +  id: string;
Будь ласка, перевір чи тут все ок з відступами (має бути 4 пробіли). Інколи Github їх неправильно відображає.

Але якщо насправді тут 2 пробіли відступ і лінтер не створює помилку - дай знати, я буду розбиратись з цим

2023-02-13 12:45 UTC, dreyliky commented on apps/code-review/src/app/pages/request/request.component.html
> +<acua-requests-table></acua-requests-table>
Давай замінимо хардкодні блоки на сторінці `list` на таблиці. А звідци приберемо цю таблицю

2023-02-13 12:45 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/user-avatar/user-avatar.component.ts
> +import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
Давай винесемо цей компонент в `libs/shared/src/lib/components/avatar/avatar.component|module.ts`.

Цей компонент буде приймати на вхід @Input параметр `url: string`.

2023-02-13 12:45 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/user-avatar/user-avatar.component.html
> +<img
Давай приберемо звідси `img` і зробимо накладання `background-image` на host компонент через `@HostBinding`.

Можна видалити `html` файл для цього компоненту, бо він нам не потрібен.

Перевага буде в тому що можна буде доволі просто змінювати розміри аватару ззовні через CSS накладаючи стилі на цей компонент.

2023-02-13 12:45 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/user-avatar/user-avatar.component.ts
> +  @Input() public userAvatarSrc!: string;
Давай будемо додавати enter між декоратором і полем.

І між огорнутими в декоратор полями також будемо додавати enter.

Буде так:
```
@Input()
public url!: string;

@Input()
public someField!: SomeType;
```

2023-02-13 12:45 UTC, dreyliky commented on apps/code-review/src/app/pages/request/request.module.ts
> +import { RequestsTableComponent } from './components/requests-table/requests-table.component';
Відсутні index.ts файли для спрощення імпортів

2023-02-13 12:45 UTC, dreyliky commented on apps/code-review/src/app/remote-entry/entry.routes.ts
> +                path:  `${AppRouteEnum.Overview}/:id`,
Цей параметр має бути винесеним в enum. Наприклад: `OverviewParamEnum` який би лежав в: `pages/overview/enums`.

Також, давай цей `:id` параметр винесемо в маршрутизацію сторінки `Overview` бо це деталі саме цієї сторінки, на цьому рівні має бути просто опис того що є така сторінка `Overview`, а всі її параметри або дочірні маршрути вже описуються всередині.

2023-02-13 12:45 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/requests-table/requests-table.component.ts
> +    public dataSource = ELEMENT_DATA;
Відсутній `readonly`

2023-02-13 12:45 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/requests-table/requests-table.component.ts
> +    public displayedColumns: string[] = ['name', 'date', 'user'];
Відсутній `readonly`

2023-02-13 12:45 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/user-avatar/user-avatar.component.html
> +  [matTooltip]="userName || ''"
Після винесення цього компоненту в `libs/shared` треба буде звідси прибрати `matTooltip` і накидати його на конкретній сторінці.

2023-02-13 12:45 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/requests-table/requests-table.component.ts
> +    public handleTableRowClick(id: number): void {
Давай будемо називати обробники з префіксу `on`. Наприклад:
`onCodeReviewRequestClick(data: CodeReviewRequest): void { ... }`

2023-02-13 12:45 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/requests-table/requests-table.component.ts
> +    constructor(private readonly _router: Router) {}
Давай не будемо використовувати `_` для приватних полів в цьому проєкті. Лише в випадках виключення: Наприклад колізія імен.

2023-02-13 12:45 UTC, dreyliky commented on apps/code-review/src/app/core/interfaces/code-review-request.interface.ts
> +export interface CodeReviewRequest {
Всі поля всіх інтерфейсів мають мати `readonly` для запобігання випадкових мутацій даних

2023-02-13 12:45 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/requests-table/requests-table.component.ts
> +];
Має бути enter між константою і декоратором

2023-02-13 12:45 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/requests-table/requests-table.component.html
> +<mat-table
Цей компонент має бути частиною сторінки `list`.

2023-02-13 19:44 UTC, yatsivroge commented on apps/code-review/src/app/core/interfaces/code-review-request.interface.ts
> +  id: string;
В мене лінтер не створює помилки, там два рядки

2023-02-14 07:52 UTC, yatsivroge commented on apps/code-review/src/app/pages/request/components/requests-table/requests-table.component.ts
> +    constructor(private readonly _router: Router) {}
done

2023-02-14 07:53 UTC, yatsivroge commented on apps/code-review/src/app/core/interfaces/code-review-request.interface.ts
> +export interface CodeReviewRequest {
done

2023-02-14 07:53 UTC, yatsivroge commented on apps/code-review/src/app/pages/request/components/requests-table/requests-table.component.ts
> +];
done

2023-02-14 07:53 UTC, yatsivroge commented on apps/code-review/src/app/pages/request/components/requests-table/requests-table.component.html
> +<mat-table
done

2023-02-14 07:58 UTC, yatsivroge commented on apps/code-review/src/app/pages/request/components/requests-table/requests-table.component.ts
> +    public handleTableRowClick(id: number): void {
done

2023-02-14 07:58 UTC, yatsivroge commented on apps/code-review/src/app/pages/request/components/requests-table/requests-table.component.ts
> +    public displayedColumns: string[] = ['name', 'date', 'user'];
done

2023-02-14 07:58 UTC, yatsivroge commented on apps/code-review/src/app/pages/request/components/requests-table/requests-table.component.ts
> +    public dataSource = ELEMENT_DATA;
done

2023-02-14 19:09 UTC, yatsivroge commented on apps/code-review/src/app/core/enums/code-review-status-enum.ts
> +export enum CodeReviewStatusEnum {
тут трохи не зрозумів, получається зробити папку  енамс на томо ж рівні як кор і туда це запхнути?

2023-02-14 19:17 UTC, yatsivroge commented on apps/code-review/src/app/pages/request/components/user-avatar/user-avatar.component.ts
> +import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
done

2023-02-14 19:17 UTC, yatsivroge commented on apps/code-review/src/app/pages/request/components/user-avatar/user-avatar.component.ts
> +  @Input() public userAvatarSrc!: string;
done

2023-02-14 19:17 UTC, dreyliky commented on apps/code-review/src/app/core/enums/code-review-status-enum.ts
> +export enum CodeReviewStatusEnum {
Так. Всі конкретні речі складаємо на рівні app, а базові речі в core.

Базова річ: ApiService.
Конкретна річ: UserApi.

Базова річ: AppRouteEnum.
Конкретна річ: HomeRouteEnum (кладемо в папку enums в папці сторінки).

2023-02-14 19:18 UTC, yatsivroge commented on apps/code-review/src/app/pages/request/request.module.ts
> +import { RequestsTableComponent } from './components/requests-table/requests-table.component';
done

2023-02-17 07:25 UTC, yatsivroge commented on apps/code-review/src/app/pages/request/components/user-avatar/user-avatar.component.html
> +<img
done

2023-02-17 15:08 UTC, yatsivroge commented on apps/code-review/src/app/core/enums/code-review-status-enum.ts
> +export enum CodeReviewStatusEnum {
done

2023-02-17 15:08 UTC, yatsivroge commented on apps/code-review/src/app/core/interfaces/code-review-request.interface.ts
> +import { CodeReviewStatusEnum } from '@code-review/core';
done

2023-02-17 15:09 UTC, yatsivroge commented on apps/code-review/src/app/pages/request/request.component.html
> +<acua-requests-table></acua-requests-table>
не знаю чи я правильно зрозумів, але замінив

2023-02-17 15:20 UTC, yatsivroge commented on apps/code-review/src/app/remote-entry/entry.routes.ts
> +                path:  `${AppRouteEnum.Overview}/:id`,
done

2023-02-17 16:24 UTC, dreyliky requested changes

2023-02-17 16:24 UTC, dreyliky commented on apps/code-review/src/app/core/interfaces/index.ts
> +
Пустий файл

2023-02-17 16:24 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/enums/overview-param.enum.ts
> +  id = ':id'
Параметр тут має бути без `:`, щоб його можна було діставати з `ActivatedRoute`.

2023-02-17 16:24 UTC, dreyliky commented on libs/shared/src/lib/components/user-avatar/user-avatar.component.ts
> +    HostBinding, OnInit
Enter

2023-02-17 16:24 UTC, dreyliky commented on libs/shared/src/lib/components/user-avatar/user-avatar.component.ts
> +    public userAvatarUrl!: string;
`avatarUrl`

2023-02-17 16:24 UTC, dreyliky commented on libs/shared/src/lib/components/user-avatar/user-avatar.component.ts
> +  public ngOnInit(): void {
ngOnChanges

2023-02-17 16:24 UTC, dreyliky commented on apps/code-review/src/app/pages/list/list.component.html
> +          <acua-requests-table></acua-requests-table>
Таблиця має бути всередині компонентів: `<acua-all-requests></acua-all-requests>`, `<acua-my-requests></acua-my-requests>`, `<acua-historical-requests></acua-historical-requests>`.

В середині цих компонентів треба замінити якісь хардкодні блоки

2023-02-17 16:24 UTC, dreyliky commented on libs/shared/src/lib/components/user-avatar/user-avatar.component.ts
> +      }
else - має бути знову default аватар. Цей else буде актуальний, коли ми замінимо `ngOnInit` на `ngOnChanges`.

Справа в тому що компонент має динамічно оновлювати аватар. Це може бути необхідно робити

2023-02-17 16:28 UTC, yatsivroge commented on apps/code-review/src/app/core/interfaces/index.ts
> +
done

2023-02-17 16:34 UTC, yatsivroge commented on libs/shared/src/lib/components/user-avatar/user-avatar.component.ts
> +    HostBinding, OnInit
done

2023-02-17 16:34 UTC, yatsivroge commented on libs/shared/src/lib/components/user-avatar/user-avatar.component.ts
> +    public userAvatarUrl!: string;
done

2023-02-17 16:41 UTC, yatsivroge commented on libs/shared/src/lib/components/user-avatar/user-avatar.component.ts
> +  public ngOnInit(): void {
done

2023-02-17 16:45 UTC, yatsivroge commented on apps/code-review/src/app/pages/list/list.component.html
> +          <acua-requests-table></acua-requests-table>
done

2023-02-17 16:45 UTC, yatsivroge commented on libs/shared/src/lib/components/user-avatar/user-avatar.component.ts
> +      }
done

2023-02-17 16:52 UTC, dreyliky approved these changes

2023-02-18 17:18 UTC, merged