refactor(code-review): refactored file explorer, tree, moved icons to shared assets
dreyliky/angular-community-ua-frontend pull request #41
Opened 2023-02-14 19:26 UTC by br1ttan

2023-02-14 19:29 UTC, br1ttan commented
хотілось би дізнатись як такі великі гетери та методи скорочувати нормально=)

2023-02-16 17:01 UTC, dreyliky requested changes

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.html
> +    (click)="onButtonToggle()"
Давай будемо сортувати біндінги і події. Спочатку всі біндінги + атрибути, а під ними - події

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +    Component, Input
Enter

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +import { FileExplorerThemeEnum } from '../../enums/file-explorer-theme.enum';
`../enums`

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +    public get getClassesAndIfOpen(): string {
Давай назвемо геттер `arrowCssClassesAsString`

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +        return `./assets/icons/file-explorer/${this.icon}.svg`;
`/assets/...`

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +    public get getClassesAndIfHide(): string {
Давай назвемо геттер `rowCssClassesAsString`

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +    private get icon(): string {
Давай переробимо це на поле, яке будемо ініціалізувати в `ngOnChanges` (запускаючи код який зараз в геттері).

Тому що виглядає комплексно як для геттера, який викликаєтся з кожною хвилею ChangeDetection

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/file-explorer.component.ts
> +    Component, Input
Enter

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +        if (Object.keys(folders).includes(this.name)) {
Зайвий цикл. Має бути `if (folders[this.name]) {`

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +    private getFolders(): string {
Давай замінимо 2 методи `getFolders` & `getDifferentFolders` на один метод:

```
private getFolderIconName(): string {
    let folderName = 'folder';

    if (folders[this.name]) {
        folderName = folders[this.name as keyof typeof folders];
    }
    
    if (this.isOpened) {
        return `${folderName}-open`;
    }

    return folderName;
}
```

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +import { extensions, files, folders } from '../../data';
Всі ці константи давай назвемо з великих літер.

Кожна константа нехай має додаткове ключов слово `MAPPER`, наприклад: `FOLDER_ICON_NAME_MAPPER`.

Це буде означати що по назві папки ми будемо отримувати назву іконку цієї папки.

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +        return `${10 * this.depth}px`;
Давай винесемо `10` в:
`private readonly baseMarginLeft = 10;`

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +    public get isHide(): boolean {
`isHidden`

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +    public get isContent(): boolean {
`isContentExist`

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +    public get depthIncrement(): number {
`incrementedDepth`

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +        if (Object.keys(files).includes(this.name)) {
`if (files[this.name]) {`

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +    private getFiles(): string {
`getFileIconName`

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +    private getExtensions(splittedName: string): string {
`getExtensionIconName`

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/enums/file-explorer-theme.enum.ts
> +export enum FileExplorerThemeEnum {
Прибираємо все що пов'язано з темами

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/file-explorer.component.html
> +        *ngFor="let row of tree"
Давай будемо структурні директиви першими

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/file-explorer.component.html
> +<div [style.width]="width" [style.height]="height" [class]="theme">
Зайвий div. Прибираємо. В нас вже є HOST який ми можемо використовувати як обгортку

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/file-explorer.component.ts
> +    public width = '300px';
Прибираємо цей input параметр. Якщо хочеться змінити ширину - накладаємо клас на host і змінюємо ширину host елементу

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/file-explorer.component.ts
> +    public height = '500px';
Прибираємо цей input параметр. Якщо хочеться змінити висоту - накладаємо клас на host і змінюємо висоту host елементу

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/file-explorer.component.ts
> +    public theme: FileExplorerThemeEnum = FileExplorerThemeEnum.Dark;
Прибираємо все що пов'язано з темами

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/interfaces/element-offset-position.interface.ts
> +export interface ElementOffsetPosition {
Виглядає як щось що не треба

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +    public theme: FileExplorerThemeEnum = FileExplorerThemeEnum.Dark;
Прибираємо

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +            if (Object.keys(extensions).includes(nameArray.join('.'))) {
```
const possibleExtensionName = nameArray.join('.');

if (extensions[possibleExtensionName]) {
```

2023-02-16 17:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +        let nameArray = this.name.split('.');
Виносимо все аж до `return 'file'` в метод: `getExtensionIconName`.

Тут пишимо:
```
const extensionIconName = this.getExtensionIconName();

if (extensionIconName) {
    return extensionIconName;
}

return 'file';
```

2023-02-16 20:45 UTC, dreyliky requested changes

2023-02-16 20:45 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +        this.initializeIcon();
Давай просто напишемо тут:
`this.icon = this.getIcon();`

2023-02-16 20:45 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +    private initializeIcon(): void {
Цей метод приберемо

2023-02-16 20:45 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +
Давай тут над класом зробимо такі типи:
```
type ExtensionName = keyof typeof EXTENSION_ICON_NAME_MAPPER;
type FileName = keyof typeof FILE_ICON_NAME_MAPPER;
type FolderName = keyof typeof FOLDERS_ICON_NAME_MAPPER;
```

Щоб ними оперувати більш красиво і компактно було в самому коді.

2023-02-17 11:42 UTC, dreyliky requested changes

2023-02-17 11:42 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/file-explorer/components/file-tree-node/file-tree-node.component.ts
> +        const NAME_AS_FOLDER_NAME = this.name as FolderName;
Локальні константи не варто писати з великих літер. Ну а для простоти можна одразу писати `this.name as FolderName` в Mapper

2023-02-17 11:46 UTC, dreyliky approved these changes

2023-02-17 11:49 UTC, merged