Adjusting Monaco Editor #1
dreyliky/angular-community-ua-frontend pull request #48
Opened 2023-02-18 22:45 UTC by AndreyBuvria

Додав трохи функціоналу та деякі обробники на дії в моделі.

2023-03-01 15:01 UTC, dreyliky requested changes
Прошу одразу рендерити кружечки з кількістю коментів на кожному рядку де є коменти (а не тільки при наведенні). Те ж саме з підсвідкою рядку - легке підсвічування рядку де є коментарі - при наведені підсвідка стає сильнішою

2023-03-01 15:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/code-editor/code-editor.component.scss
> +.selected-line {
Занадто абстрактно як для глобального класу. Давай додамо префікс щоб було типу `acua-editor-selected-line`

2023-03-01 15:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/code-editor/code-editor.component.ts
> +    Component, Inject, ViewEncapsulation
Давай додамо тут ентери

2023-03-01 15:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/code-editor/code-editor.component.ts
> +    LineCommentsAmountDirective, LineHighlighterDirective
Ентер

2023-03-01 15:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/code-editor/components/comments-amount/comments-amount.component.html
> +<div class="counter">
Можемо тут все прибрати і залишити тільки `{{ amount }}`

2023-03-01 15:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/code-editor/components/comments-amount/comments-amount.component.scss
> +.counter {
Можемо тут накласти стилі просто на `:host` елемент

2023-03-01 15:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/code-editor/directives/cursor-style.directive.ts
> +import { Directive, Inject, OnInit, Renderer2 } from '@angular/core';
Чи можемо ми прибрати взагалі цю директиву і одразу накладати `cursor: pointer` на елемент `acua-code-editor` в його ж стилях?

2023-03-01 15:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/code-editor/directives/line-comments-amount.directive.ts
> +    Inject, ViewContainerRef
Ентер

2023-03-01 15:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/code-editor/directives/line-comments-amount.directive.ts
> +        private readonly componentFactoryRef: ComponentFactoryResolver
`componentFactory` deprecated. Використовуй `this.viewContainerRef.createComponent`

2023-03-01 15:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/overview.component.ts
> +    ChangeDetectionStrategy, Component, ViewChild
Enters

2023-03-01 15:01 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/overview.component.ts
> +import { MONACO_EDITOR_PROVIDER } from './components/code-editor/providers';
index.ts

2023-03-01 23:20 UTC, AndreyBuvria commented on apps/code-review/src/app/pages/overview/components/code-editor/directives/cursor-style.directive.ts
> +import { Directive, Inject, OnInit, Renderer2 } from '@angular/core';
Я був би радий так зробити але воно не застовується

2023-03-05 18:00 UTC, dreyliky approved these changes

2023-03-05 18:00 UTC, merged