feat(code-review): added request creation page
dreyliky/angular-community-ua-frontend pull request #51
Opened 2023-02-21 12:53 UTC by vitalikyarina

2023-02-21 14:34 UTC, dreyliky requested changes

2023-02-21 14:34 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/request-form/request-form.component.html
> +        <input matInput type="text" formControlName="name" />
Давай не будемо використовувати хардкодні рядки для вказання formControl'ів. Пропоную замінити `formControlName` на `formControl` директиву в усіх місцях.

2023-02-21 14:34 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/request-form/request-form.component.ts
> +    selector: 'acua-request-from'
CDR OnPush missed

2023-02-21 14:34 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/request-form/request-form.component.ts
> +        return new FormGroup({
Давай винесемо опис FormGroup в окремий клас, приблизно як в цьому прикладі:
https://stackblitz.com/edit/angular-ivy-l8cyne?file=src%2Fapp%2Fforms%2Fuser.form.ts.

Цей клас має бути локальний для сторінки `Request`.
Запровайдимо цей `RequestForm` клас на рівні `RequestComponent` компоненті.

2023-02-21 14:34 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/request-form/request-form.component.ts
> +        private requestApiService: RequestApiService,
Компоненти не мають працювати напряму з логічними прошарками `API` чи `State` . Компоненти працюють з бізнес логікую тільки через прошарки сервісів чи фасадів. В нашому випадку - варто зробити окремий service, який вже буде працювати з API

2023-02-21 14:34 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/request-form/request-form.component.ts
> +        this.form = this.createForm();
Форма створюється 2 рази.

2023-02-21 14:34 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/request-form/request-form.component.ts
> +    protected hasControlError(controlName: string): boolean {
Після винесення форми в окремий клас, коли вона буде типізованою - ми будемо звертатися в HTML напряму до: `form.controls.myControl.hasErrors()` (чи щось подібне)

2023-02-21 14:34 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/request-form/request-form.component.html
> +        <mat-error *ngIf="hasControlError('link')">
В описі задачі вказано, що помилка має писатися в форматі тексту. В залежності від типу помилки - текст буде різним

2023-02-21 14:34 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/request-form/request-form.component.ts
> +    private updateIframeLink(): void {
Давай переробимо цей код на декларативний підхід, де вся ця логіка буде описана в Observable, а підписка буде в template через `async` пайп.

2023-02-21 14:34 UTC, dreyliky commented on apps/code-review/src/app/pages/request/request.component.ts
> +    @ViewChild('form') protected requestForm!: RequestFormComponent;
Давай приберемо звідси `ViewChild`. Ми будемо мати тут доступ до форми через `DI`

2023-02-21 14:34 UTC, dreyliky commented on apps/code-review/src/app/pages/request/request.component.ts
> +    constructor(private router: Router) {}
`readonly`

2023-02-21 14:34 UTC, dreyliky commented on apps/code-review/src/app/shared/api/request-api.service.ts
> +    private apiUrl = 'http://161.35.70.152:3001';
Цей URL має бути винесений в environments. Давай зробимо `environments` в цьому проєкті по аналогії з проєктом `host`. Вони мають бути під'єднані в `project.json`. Наразі зробимо там одне поле: `backendUrl`.

Працювати з `environment` треба через DI. Чекни також як це зроблено в `host` проєкті

2023-02-21 14:34 UTC, dreyliky commented on apps/code-review/src/app/shared/api/request-api.service.ts
> +    constructor(private http: HttpClient) {}
`readonly`

2023-02-21 14:34 UTC, dreyliky commented on apps/code-review/src/app/shared/validators/link-validate.validator.ts
> +export class LinkValidateValidator {
Давай зробимо валідатор класичним підходом: Injectable клас, який буде інджектуватись в `RequestForm`:
https://angular.io/guide/form-validation#implementing-a-custom-async-validator

Не треба ніяких `static` методів.

Також, давай перемістимо цей validator на рівень сторінки `request`, бо це однозначно локальна сутність тієї сторінки

2023-02-21 14:34 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/request-form/request-form.component.ts
> +        return new FormGroup({
Дані які описує форма мають мати свій інтерфейс. Наприклад: `ReviewRequestInfo`.

Також, в прикладі який я навів вище - є такий тип як `FormGroupDef`. Давай скопіюємо його собі. В ідеалі якось щоб він був одразу доступний для всіх проєктів, але з цим треба розбиратись. Якщо вийде одразу для всіх проєктів - круто, якщо ні - то поки тоді локально зробимо його

2023-02-21 14:34 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/request-form/request-form.component.ts
> +    @Output() public submitForm = new EventEmitter();
Цей Output не треба буде коли ми винесемо форму в окремий Injectable клас.

2023-02-21 14:34 UTC, dreyliky commented on apps/code-review/src/app/pages/request/request.component.ts
> +    protected onSubmitForm(formData: any): void {
Ніяких `any`

2023-02-21 14:34 UTC, dreyliky commented on apps/code-review/src/app/pages/request/request.component.ts
> +        this.router.navigateByUrl('/overview');
Сторінка `Overview` вже описана в `Enum`. То ж давай будемо прив'язуватись до значень з єнамів.

Абсолютний редірект некоректний в контексті архітектури мікрофронтендів. Спробуй клікнути на кнопку в контексті запущенного `Host` застосунку. Router буде взятий з Host застосунку і він буде шукати шлях `overview` в глобальних роутах `host` проєкту.

То ж для редіректів в `remote` застосунках, будемо використовувати `relative` редіректи.

2023-02-21 14:34 UTC, dreyliky commented on apps/code-review/src/app/pages/request/request.component.ts
> +    protected click(): void {
Методи-обробники мають мати префікс `on`. В нашому випадку це буде: `onRequestCreationButtonClick`

2023-02-21 14:34 UTC, dreyliky commented on apps/code-review/src/app/pages/request/request.component.ts
> +    protected get disabled(): boolean {
Можна буде взяти цей стан, звертаючись до `RequestForm` напряму. Можна заінджектувати:
`public readonly requestForm: RequestForm`

І в шаблоні брати `requestForm.isDisabled` (це був би геттер в класі `RequestForm`)

2023-02-21 15:32 UTC, vitalikyarina commented on apps/code-review/src/app/pages/request/request.component.ts
> +    protected get disabled(): boolean {
А хіба це буде доречно якщо isDisabled в RequestForm буде відповідати за те чи доступна кнопка чи ні. Як на мене isDisabled мав би відповідати за доступність самої форми

2023-02-21 15:55 UTC, dreyliky commented on apps/code-review/src/app/pages/request/request.component.ts
> +    protected get disabled(): boolean {
@vitalikyarina так, ти правий. Тоді просто звертайся до поля `valid` напряму)

2023-02-22 15:20 UTC, dreyliky requested changes

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/request-form/request-form.component.ts
> +    protected nameControl!: FormControl;
Давай приберемо всі FormControl звідси і будемо в HTML напряму звертатися до `form.controls.myControl`

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/request-form/request-form.component.ts
> +        this.iframeLink$ = this.getIframeLink();
Тут може бути спам викликів на бекенд. Я розумію що ймовірно посилання буде вставлятися з буферу, але енівей варто мінімізувати кількість викликів цієї логіки і зробити більш оптимізований підхід.

Наприклад, я вставив посилання не те, або в буфері було не те значення. Я почну стирати його і буде величезний спам викликів на бекенд

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/request-form/request-form.component.ts
> +        return this.form.value;
Не бачу сенсу в цьому геттері

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/request-form/request-form.component.ts
> +        return this.form.valid;
Не бачу сенсу в цьому геттері

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/src/app/pages/request/interfaces/request-form-info.interface.ts
> +    readonly link: string | null;
link не може бути null

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/src/app/pages/request/interfaces/request-form-info.interface.ts
> +    readonly description: string;
Optional

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/request-form/request-form.component.ts
> +        this.nameControl = this.form.get('name') as FormControl;
Завдяки `FormGroupDef` типу, в нас і так кожен control буде як FormControl. То ж можна звертатися напряму до `form.controls.myControl`

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/request-form/request-form.component.ts
> +        protected form: RequestForm,
Кожне поле яке не має змінюватись має мати `readonly`. А поле можна назвати `formGroup`

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/src/app/pages/request/request.component.ts
> +    protected get disabled(): boolean {
`isRequestCreationButtonDisabled`.

`disabled` в контексті класу `RequestComponent` звучить так, наче наша сторінка `disabled`

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/src/app/pages/request/request.component.html
> +    <acua-request-from #form></acua-request-from>
Можемо прибрати `form` template variable

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/src/app/pages/request/validators/link-validate.validator.ts
> +import { RequestService } from '../../../shared/services';
Давай підправимо імпорт, зробимо його через path alias

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/src/app/pages/request/validators/link-validate.validator.ts
> +    providedIn: 'root'
Давай запровайдимо його локально на рівні сторінки

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/src/app/pages/request/validators/link-validate.validator.ts
> +        control: AbstractControl<any, any>
`AbstractControl<string, string>` наскільки я розумію має бути

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/src/app/pages/request/validators/link-validate.validator.ts
> +    ): Observable<ValidationErrors | null> | Promise<ValidationErrors | null> {
Return type `Observable<ValidationErrors | null>`

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/src/app/shared/services/request.service.ts
> +export class RequestService {
`project-source-url.service`, `ProjectSourceUrlService`.

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/src/app/shared/api/request-api.service.ts
> +export class RequestApiService {
`project-source-url.api.ts`, `ProjectSourceUrlService`

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/src/app/shared/api/request-api.service.ts
> +    public validateLink(link: string): Observable<boolean> {
`validate`

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/src/app/shared/api/request-api.service.ts
> +    public getNormalizedLink(link: string): Observable<string> {
`getNormalized`

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/src/app/shared/index.ts
> +export * from '../pages/request/validators';
Невалідний експорт

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/tsconfig.editor.json
> +    "include": ["src/**/*.ts", "../../libs/shared/src/lib/pipes/safe.pipe.ts"],
Для чого це?

2023-02-22 15:20 UTC, dreyliky commented on libs/shared/src/lib/pipes/safe.pipe.ts
> +    constructor(private sanitizer: DomSanitizer) {}
`readonly`

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/src/app/pages/request/interfaces/request-form-info.interface.ts
> +export interface RequestFormInfo {
Давай винесемо цей інтерфейс в `shared` папку проєкту `code-review`. Причина: Нехай бізнес логіка (сервіси, апі, стейти) знаходяться глобально, а конкретні реалізації UI на базі глобальної бізнес логіки - на конкретних сторінках.

В цьому випадку, пропоную назвати інтерфейс також `ReviewRequestInfo`

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/request-form/request-form.component.ts
> +    private getIframeLink(): Observable<string> {
`getIframeLinkObservable`. Мені здається на рівні компоненту корисно уточнити в методі, що він повертає саме Observable. Проте звісно це суб'єктивне зауваження

2023-02-22 15:20 UTC, dreyliky commented on apps/code-review/src/app/pages/request/components/request-form/request-form.component.ts
> +                const value = this.linkControl.value as string;
А що, `linkControl.value` зараз не типу `string`? Бтв буде `this.formGroup.controls.link.value`

2023-02-22 17:38 UTC, dreyliky requested changes

2023-02-22 17:38 UTC, dreyliky commented on apps/code-review/src/app/shared/api/project-source-url.api.ts
> +import { environment } from 'apps/code-review/src/environments/environment';
Давай будемо використовувати DI для роботи з environment. Чекни як це зроблено в `host` проєкті

2023-02-22 17:39 UTC, dreyliky requested changes

2023-02-22 17:39 UTC, dreyliky commented on libs/shared/src/lib/pipes/safe.pipe.ts
> +    name: 'safe'
`safeResourceUrl`

2023-02-22 17:39 UTC, dreyliky commented on libs/shared/src/lib/pipes/safe.pipe.ts
> +export class SafePipe implements PipeTransform {
SafeResourceUrlPipe

2023-02-22 17:42 UTC, dreyliky requested changes

2023-02-22 17:42 UTC, dreyliky commented on apps/code-review/src/app/shared/api/project-source-url.api.ts
> +    constructor(private readonly http: HttpClient) {}
`readonly`

2023-02-22 17:44 UTC, dreyliky requested changes

2023-02-22 17:44 UTC, dreyliky commented on apps/code-review/src/app/shared/services/project-source-url.service.ts
> +    constructor(private projectSourceUrlApi: ProjectSourceUrlApiService) {}
`readonly`

2023-02-22 18:02 UTC, dreyliky approved these changes

2023-02-22 19:59 UTC, merged