feat(code-review): add header overview page
dreyliky/angular-community-ua-frontend pull request #52
Opened 2023-02-27 18:20 UTC by DenysSkobalo

2023-02-27 20:51 UTC, dreyliky requested changes

2023-02-27 20:51 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/header/header.component.html
> +<header *ngIf="isMobile; else desktopTemplate">
Давай приберемо тут дубльований код. Маю на увазі `header` & `div class="container"` & `icon-button menu`.

Тобто, просто зроби 2 `ngIf` - з умовою на елементі `accordion` & з умовою на кнопці `Деталі`.

Відповідно приберемо `ng-template` тут також)

2023-02-27 20:51 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/header/header.component.html
> +                    (opened)="panelOpenState = true"
Давай винесемо це на рівень Typescript. Для написання подібного коду є Typescript. Зробимо обробники `onRequestAccordionOpened` & `onRequestAccordionClosed` обробники

2023-02-27 20:51 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/header/header.component.ts
> +        private deviceService: DeviceDetectorService,
`readonly` для полів

2023-02-27 20:51 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/header/header.component.ts
> +        public dialog: MatDialog
`private readonly`

2023-02-27 20:51 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/header/header.component.ts
> +    public openDialog(): void {
`onDetailsButtonClick`

2023-02-27 20:51 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/header/header.component.ts
> +        this.isMobile = this.deviceService.isMobile();
Можемо одразу записати це в поле на рядку 14

2023-02-27 20:51 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/header/review-request-details-window/review-request-details-window.component.ts
> +export class ReviewRequestDetailsWindowComponent {
Можемо зробити цей клас пустим. Логіку закриття вікна можна зробити навісивши директиву від Material яка сама зачинить вікно

2023-02-27 20:51 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/header/review-request-details-window/review-request-details-window.component.html
> +    <button mat-button (click)="onClose()" class="btn-close">Закрити</button>
Давай додамо директиву `mat-dialog-close` яка буде зачиняти вікно. Обробник можна прибрати

2023-02-27 20:51 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/header/review-request-details-window/review-request-details-window.component.scss
> +.btn-close {
Погані стилі. Тут не треба ніяких абсолютів. У компоненту `mat-dialog-actions` є інпут параметр для розміщення кнопок справа

2023-02-27 20:51 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/overview.component.scss
> +    position: absolute;
Давай без абсолюту для контейнеру

2023-02-27 20:51 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/overview.module.ts
> +import { HeaderModule } from './components/header/header.module';
Підправ імпорт, щоб він був з `'./components';` і об'єднай його з рядком 4

2023-03-07 08:58 UTC, dreyliky requested changes

2023-03-07 08:58 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/header/header.component.html
> +<header *ngIf="!isMobile">
Давай приберемо умови з елементів `header`. Замість цього об'єднаємо контент з другого header в перший (кнопка details) і накладемо умови на: `details button` & `mat-accordion`

2023-03-07 08:58 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/header/header.component.html
> +                            matTooltip="UserName"
```suggestion
                            [matTooltip]="'UserName'"
```

2023-03-07 08:58 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/header/header.component.ts
> +    public panelOpenState = false;
Я не розумію для чого зараз зберігається ця інформація?

2023-03-07 08:58 UTC, dreyliky commented on apps/code-review/src/app/pages/overview/components/header/review-request-details-window/review-request-details-window.component.html
> +<mat-dialog-actions align="end">
```suggestion
<mat-dialog-actions [align]="'end'">
```

2023-03-07 12:16 UTC, br1ttan commented on apps/code-review/src/app/pages/overview/overview.component.scss
>      display: flex;
Тут також треба прибрати цей дісплей флекс

2023-03-11 15:08 UTC, dreyliky approved these changes

2023-03-11 15:10 UTC, merged