feat(code-review): add markdown support
dreyliky/angular-community-ua-frontend pull request #55
Opened 2023-03-18 17:32 UTC by br1ttan

2023-03-18 17:35 UTC, br1ttan commented
Зробив всю логіку в eidtor component, тому що ніяк не можу придумати як брати з методу renderAsMarkdownIt дані з подальшим передаванням їх до preview component

2023-04-10 12:20 UTC, dreyliky requested changes

2023-04-10 12:20 UTC, dreyliky commented on apps/code-review/src/app/pages/list/list.module.ts
> +import { MarkdownComponent } from './components/markdown';
`from './components'`

2023-04-10 12:20 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/classes/bold-button.class.ts
> +        return MARKDOWN_MAP.get(this.markdownSyntaxEnum)!;
```suggestion
        return `**${markdownText.trim()}**`;
```

Замість всього що є в методі і так в кожному відповідному класі

2023-04-10 12:20 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/classes/bold-button.class.ts
> +import { MarkdownButton } from '../interfaces/markdown-button.interface';
```suggestion
import { MarkdownButton } from '../interfaces';
```

І так в кожному відповідному класі

2023-04-10 12:20 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/components/markdown-editor-button.components.ts
> +    public enumEmitter = new EventEmitter<Event>();
Прибираємо цей output. Він не потрібен. Ми можемо одразу накладати `(click)` на компонент

2023-04-10 12:20 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/data/markdown-data.array.ts
> +import { HeaderButtonClass } from '../classes/header-button.class';
Об'єднати імпорт в перший рядок

2023-04-10 12:20 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/directives/mardown-editor-selection.directive.ts
> +            return this.insertMarkdownWithoutSelection(markdownButton);
Метод `insertMarkdownWithoutSelection` нічого не повертає. А значить `return` Не треба. Замість цього, виклик методу нижче треба запхнути всередину `else`

2023-04-10 12:20 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/directives/mardown-editor-selection.directive.ts
> +        const selectedPositions = this.getSelectedPositions();
```suggestion
        const { start, end } = this.getSelectedPositions();
```

2023-04-10 12:20 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/directives/mardown-editor-selection.directive.ts
> +        const markdownItText = new MarkdownIt().render(this.hostRef.nativeElement.value);
Давай створемо інстанс MarkdownIt 1 раз і запишемо в поле класу. А тут вже будемо звертатися до поля і викликати render. Також цю константу можна не робити, а одразу return

2023-04-10 12:20 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/enums/markdown-syntax.enum.ts
> +export enum MarkdownSyntaxEnum {
```suggestion
export enum MarkdownActionEnum {
```

2023-04-10 12:20 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/markdown-editor.component.html
> +                (enumEmitter)="insertMarkdownSyntax(button)"
click

2023-04-10 12:20 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/markdown-editor.component.ts
> +    public insertMarkdownSyntax(markdownButton: MarkdownButton): void {
```suggestion
    public onMarkdownButtonClick(markdownButton: MarkdownButton): void {
```

2023-04-11 13:02 UTC, dreyliky requested changes

2023-04-11 13:02 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/directives/mardown-editor-selection.directive.ts
> +    selector: '[markdownEditorSelector]'
markdownEditorInput

Так само і клас давай перейменуємо + файл. Що таке Selector - не зрозуміло

2023-04-11 13:02 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/directives/mardown-editor-selection.directive.ts
> +    private getSelectedPositions(): { start: number; end: number } {
Над цим класом можемо описати interface який не буде експортуватись (локальний інтерфейс)

2023-04-11 13:02 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/directives/mardown-editor-selection.directive.ts
> +    public renderAsMarkdownIt(): string {
```suggestion
    private render(): string {
```

2023-04-11 13:02 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/directives/mardown-editor-selection.directive.ts
> +    public insertMarkdownSyntax(markdownButton: MarkdownButton): void {
```suggestion
    public insertMarkdown(markdown: string): void {
```

Давай будемо ззовні отримувати вже markdown готовий і тут його вже якось рендерити. Клас сюди не будемо передавати.

Тобто тут будемо викликати також `this.render` щоб на верхньому рівні про це не думати. Верхній рівень просто передає markdown який треба відрендерити, а тут всі ці умови і процеси нехай будуть всередині

2023-04-11 13:02 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/directives/mardown-editor-selection.directive.ts
> +    public insertMarkdownWithoutSelection(markdownButton: MarkdownButton): void {
Думаю можна зробити цей метод private

2023-04-11 13:02 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/directives/mardown-editor-selection.directive.ts
> +    public insertMarkdownWithSelection(markdownButton: MarkdownButton): void {
Думаю можна зробити цей метод private

2023-04-11 13:02 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/interfaces/markdown-button.interface.ts
> +    readonly getMarkdownSyntax: (markdownText: string) => string;
```suggestion
    readonly getMarkdown(context?: string): string;
```

Цей метод на вхід приймає звичайний текст (context), а повертає текст огорнутий в синтаксис markdown.

Інколи текст на вхід може бути відсутнім (коли не виділено нічого в textarea).

2023-04-11 13:08 UTC, dreyliky requested changes

2023-04-11 13:08 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/interfaces/markdown-button.interface.ts
> +    readonly markdownSyntaxEnum: MarkdownActionEnum;
`actionType`

2023-04-11 13:14 UTC, dreyliky commented
Щодо візуальної складової. Давай зробимо щось накшталт того, як це виглядає в гітхаб. Див скрін.

Справа кнопки зверху над textarea і якось їх візуально зробити подібно до гітхабу.

![image](https://user-images.githubusercontent.com/28815991/231173884-4e4b3af3-e8e5-4e46-a803-dedc86d6140c.png)

2023-04-11 13:16 UTC, dreyliky commented
Поведінка в момент коли в нас НЕ ВИДІЛЕНИЙ текст в textarea - наразі не коректна. Треба вставити markdown синтаксис туди, де зараз знаходиться курсор. В деяких випадках треба "огорнути" курсор синтаксисом markdown, як наприклад в випадку з bold, italic операціями. В випадку з header операцією - огортати курсор не треба.

Спробуй тут в гітхабі понатискати на кнопки ці і ти зрозумієш про що я. То ж подумай як це зробити =)

2023-04-21 09:41 UTC, dreyliky commented
Поведінка стала краще. Проте є все ще неточності і баги.

1) Баг: Написати пару літер без markdown форматування і натиснути Privew - візуально нічого не відображається, а мав би бути звичайний невідформатований текст;
2) Стан Textarea не зберігається, коли ми повертаємось назад з Preview в режим редагування;
3) Візуально виглядає неприємним кнопка Preview, сірий background і textarea не в стилі Material. Спробуй взяти натхнення з Github.

Пропоную переробити все ж таки кнопку Preview на 2 кнопки: Write & Preview, які будуть на базі Material "Button Toggle".

Давай додамо Material Tooltip для кожної кнопки, де буде написано текстом за що вона відповідає (як в Github).

Давай збільшимо height textarea (приблизно як в Github).

Гілка має конфлікти з dev гілкою, треба пофіксити.

2023-04-21 09:48 UTC, dreyliky requested changes

2023-04-21 09:48 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/directives/markdown-editor-input.directive.ts
> +        if (markdown === '****') {
Це порушення принципу відкритості/закритості з SOLID.

Варто щоб на верхньому рівні не було умов, які перевіряють конкретні markdown і щось роблять.

В нас вже є відповідні класи для кожного з типів markdown. То ж, треба придумати підхід, при якому на рівні цього класу ми просто викликаємо метод будь якого класу-markdown і там відбуваються всі необхідні перевірки.

2023-04-21 09:48 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/directives/markdown-editor-input.directive.ts
> +        if (markdownContext === '# ') {
Те ж саме тут. Такі умови не припустимі. Ми маємо просто викликати метод класу-markdown і вже в залежності від конкретного класу буде всередині конкретна логіка

2023-04-21 09:53 UTC, dreyliky requested changes

2023-04-21 09:53 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/directives/markdown-editor-input.directive.ts
> +    public render(): string {
Не впевнений що це має бути публічним. Було б непогано щоб в цьому класі був 1 публічний метод який викликає все необхідне. Щоб на рівні іншого класу я не парився що мені треба викликати пару методів.

2023-04-21 09:53 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/directives/markdown-editor-input.directive.ts
> +    public insertMarkdownSyntax(markdown: string, markdownContext: string): string {
Минулого разу я писав що давай тут отримувати вже готовий markdown, а не клас. Можливо нові правки не вдасться зробити без класу який передавався би сюди. Тому, якщо так буде - то можеш передати сюди клас. Але головне щоб перевірки конкретних markdown були в відповідних класах

2023-04-26 20:45 UTC, br1ttan commented on libs/shared/src/lib/components/markdown/markdown.component.ts
> +    public onToggler(active: boolean): void {
*handleActive

2023-04-27 10:39 UTC, dreyliky requested changes

2023-04-27 10:39 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/classes/markdown-button.classes.ts
> +export class BoldMarkdownSyntax implements MarkdownSyntax {
1) 1 файл - 1 клас;
2) Назва класу нехай буде з ключевим словом "Button", замість "Syntax". Адже matIconName або tooltip не мають відношення до синтаксису маркдаун;
3) Мені не подобається поле hasDoubleSide. Нехай кожна кнопка має одразу леву і праву сторони синтаксису. Просто там де не має правої сторони, буде пустий рядок;
4) Можна замінити метод getSyntaxSides на поле: `public readonly syntaxSides = { left: '# ', right: '' }`. Прибрати поле `hasDoubleSide` - уніфікувати логіку до єдиного стандарту без перевірок на `hasDoubleSide`;
5) Що таке position?
6) UI текст має бути на українській мові (tooltip text)

2023-04-27 10:39 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/directives/markdown-editor-input.directive.ts
> +interface inputSelectionRange {
Інтерфейс з великої літери

2023-04-27 10:39 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-toggler/markdown-toggler.component.ts
> +        this.markdownState.emit(true);
Виклик події краще робити після всіх необхідних дій в компоненті (змінити місцями).

Також, краще ставити Enter між викликами методів і роботою з полями чи змінними чи константами

2023-04-27 10:39 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/markdown.module.ts
> +import { MarkdownTogglerComponent } from './components/markdown-toggler/markdown-toggler.component';
index.ts

2023-04-27 10:39 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/states/markdown-input.state.ts
> +        return new MarkdownIt().render(this.data ?? '');
Стейт не має займатися нічим окрім як роботи з даними. Це не задача стейту обробляти markdown

2023-04-27 10:39 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-previewer/markdown-previewer.component.ts
> +    constructor(public readonly markdownInputState: MarkdownInputState) {}
Нам точно тут треба цей стейт?

2023-04-27 10:39 UTC, dreyliky commented on libs/shared/src/lib/components/markdown/components/markdown-editor/markdown-editor.component.html
> +        (click)="onMarkdownButtonClick(button)"
Обробники в самий низ

2023-05-05 17:34 UTC, closed without merging